//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C_SharpLinkedListDatabase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("C_SharpLinkedListDatabase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thompson    Cindy   M		754329		8287528362	3		9
        ///Coolie      Madison D		958423		8288242123	2		3
        ///Que         Susie   S		482163		7042683265	6		23
        ///.
        /// </summary>
        public static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smith   John    S		246823		8287228074	1		23
        ///Jones   Bob     W		548637		8289862451	2		2
        ///Que     Susie   S		482163		7042683265	6		23
        ///.
        /// </summary>
        public static string faculty {
            get {
                return ResourceManager.GetString("faculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thompson    Cindy   M	
        ///	754329		8287528362	3		9
        ///Que         Susie   S		482163		7042683265
        ///	6		23
        ///
        ///Coolie      Madison D		958423		8288242123	2		3 Kevin Filanowski M 1232 1234567890 2 6
        ///Amanda Filanowski M 1233 34353462 2 3
        ///Caleb Tupone M 9001 738734578 5 5.
        /// </summary>
        public static string tadmin {
            get {
                return ResourceManager.GetString("tadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smith   John    S		246823		8287228074	1		23
        ///Jones   Bob     W		548637		8289862451	2		2
        ///Que     Susie   S		482163		7042683265	6		23
        ///Amanda 
        ///Filanowski 
        ///m
        /// 1233 
        ///34353462
        /// 2 
        ///3.
        /// </summary>
        public static string tfaculty {
            get {
                return ResourceManager.GetString("tfaculty", resourceCulture);
            }
        }
    }
}
